export const CHOICES = [
  { id: "husband", name: "Муж" },
  { id: "wife", name: "Жена" },
  { id: "daughter", name: "Дочь" },
  { id: "son", name: "Сын" },
  { id: "grandpa", name: "Дедушка" },
  { id: "grandma", name: "Бабушка" },
  { id: "father_in_husband", name: "Свёкр" },
  { id: "mother_in_husband", name: "Свекровь" },
  { id: "father_wife", name: "Tесть" },
  { id: "mother_wife", name: "Tеща" },
  { id: "father", name: "Отец" },
  { id: "mother", name: "Мать" },
  { id: "sister", name: "Сестра" },
  { id: "brother", name: "Брат" },
  { id: "l_sister", name: "Младшая Сестра" },
  { id: "l_brother", name: "Младший Брат" },
  { id: "step_daughter", name: "Приёмный Сын" },
  { id: "step_brother", name: "Приёмная Дочь" },
  { id: "step_mother", name: "Приёмная Мать" },
  { id: "step_father", name: "Приёмный Отец" },
];
